blueprint:
  name: "Zone: Play arriving/leaving media"
  description: |-
    When a person enters or leaves a zone, play a ringtone and send text-to-speech to media players:
    "<name> is <arriving/leaving>: <zone>"

  source_url: https://raw.githubusercontent.com/drewkeller/home_assistant_blueprints/refs/heads/main/zone_change_media_actions.yaml
  domain: automation

  input:
    persons:
      name: People
      selector:
        entity:
          multiple: true
          filter:
            domain: person
    arriving_media:
      name: Arriving media (optional)
      description: |-
        Leave blank if you don't want to play an "arriving" media.
        Assuming a subpath like `audio/alert.mp3`
        * If media is placed in the `www` folder
            the path is
            `/local/audio/alert.mp3`
        * If media is placed in local media storage, the path is
            `media-source://media_source/local/audio/alert.mp3`
        * If media is placed in media storage on a network share, the path is
            `media-source://media_source/local/my_share/audio/alert.mp3`
      default: ""
      selector:
        text: {}
    leaving_media:
      name: Leaving media (optional)
      description: |-
        Leave blank if you don't want to play a "leaving" media.
        See *Arriving media* for pathing info.
      default: ""
      selector:
        text: {}
    media_players:
      name: Where to play media
      selector:
        target:
          entity:
            domain: media_player
    tts_engine:
      name: Text-to-speech engine (optional)
      description: |-
        Choose the Text-to-Speech engine (e.g. Piper, Cloud TTS, Google).
        Leave blank if you don't want to play text-to-speech.
      default: ""
      selector:
        entity:
          filter:
            domain: tts
mode: single

variables:
  persons: !input persons
  arriving_media: !input arriving_media
  leaving_media: !input leaving_media
  media_players: !input media_players
  tts_engine_in: !input tts_engine
  tts_engine: '{{ tts_engine_in if tts_engine_in != "" else None }}'

triggers:
  - trigger: state
    entity_id: !input persons
    from:
      - not_home
    id: Arriving
  - trigger: state
    entity_id: !input persons
    id: Leaving
    to:
      - not_home

conditions: []

actions:
  - variables:
      person: "{{ trigger.entity_id }}"
      person_name: '{{ state_attr(trigger.entity_id, "friendly_name") if trigger.entity_id is defined else "person" }}'
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ states(trigger.entity_id) == "unavailable" }}'
        sequence: []
    default:
      - sequence:
          - variables:
              # Don't speak the location if the state is 'not_home'
              is_arriving: '{{ trigger.id == "Arriving" }}'
              is_leaving: '{{ trigger.id == "Leaving" }}'
              to_zone1: "{{ trigger.to_state.state   if trigger.to_state != None }}"
              from_zone1: "{{ trigger.from_state.state if trigger.from_state != None }}"
              to_zone: '{{ to_zone1 if to_zone1 != "not_home" else "" }}'
              from_zone: '{{ from_zone1 if from_zone1 != "not_home" else "" }}'
              media: "{{ arriving_media if is_arriving else leaving_media }}"
              zone: '{{ to_zone if is_arriving else from_zone if is_leaving else "somewhere" }}'
              media_players_list: >-
                {% set ns = namespace(entities=[]) %}
                {% if media_players.entity_id is defined %}
                  {% set ents = media_players.entity_id if media_players.entity_id is iterable and media_players.entity_id is not string else [media_players.entity_id] %}
                  {% set ns.entities = ns.entities + ents %}
                {% endif %}
                {{ ns.entities | unique | list }}
          - alias: Play audio file
            if:
              - condition: template
                value_template: '{{ media != "" }}'
            then:
              - action: media_player.play_media
                target: !input media_players
                data:
                  media_content_id: "{{ media }}"
                  media_content_type: "music"
              - alias: Wait for the first media player to finish playing the file
                wait_for_trigger:
                  - platform: template
                    value_template: "{{ not is_state(media_players_list[0], 'playing') }}"
                # safety timeout
                timeout: "00:00:10"
                continue_on_timeout: true
          - alias: Play text-to-speech
            if:
              - condition: template
                value_template: '{{ tts_engine != None }}'
            then:
              - action: tts.speak
                metadata: {}
                target:
                  entity_id: "{{ tts_engine }}"
                data:
                  cache: true
                  media_player_entity_id: "{{ media_players_list }}"
                  # Typical wording is different for different locations.
                  # For instance:
                  #  * Weird: Joe is arriving at the home   OK   : Joe is arriving at the library
                  #  * OK   : Joe is arriving home          Weird: Joe is arriving library
                  # Instead, this works more globally:
                  #  * Joe is arriving: <name of place>
                  message: "{{ person_name }} is {{ trigger.id }}: {{ zone }}"
